[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geoff3d"
version = "0.1.0"
description = "Feed-forward 3D reconstruction for UAV imagery with geometric priors"
readme = "README.md"
authors = [{ name = "yanxian" }]
requires-python = ">=3.10.0"
dependencies = [
    "einops>=0.7",
    "gradio>=5,<6",
    "gsplat",
    "huggingface_hub",
    "hydra-core",
    "lpips",
    "matplotlib>=3.7",
    "natsort",
    "numpy>=1.24",
    "omegaconf>=2.3,<2.4",
    "opencv-python-headless==4.10.0.84",
    "open3d>=0.18",
    "OpenEXR",
    "orjson",
    "pandas",
    "Pillow>=9.5",
    "pillow-heif",
    "plyfile",
    "pycolmap>=3.10,<3.12",
    "python-box",
    "PyYAML>=6",
    "rasterio>=1.3",
    "requests",
    "rerun-sdk~=0.24.1",
    "safetensors",
    "scipy>=1.10",
    "tensorboard",
    "torch==2.5.0",
    "torchvision==0.20.0",
    "tqdm",
    "trimesh",
    "uniception==0.1.6",
    "xformers==0.0.28.post2",
]

[project.optional-dependencies]
dev = ["pre-commit", "pytest", "pytest-cov", "ruff"]

# Setuptools configuration
[tool.setuptools.packages.find]
include = ["geoff3d*"]

[tool.setuptools.package-data]
"geoff3d" = ["**/*"]

[tool.ruff]
lint.extend-select = ["I"]
target-version = "py310"

[tool.ruff.lint.isort]
case-sensitive = false
combine-as-imports = true
detect-same-package = false
order-by-type = false
known-first-party = ["geoff3d", "uniception"]
