[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geoff3d"
version = "0.1.0"
description = "Feed-forward 3D reconstruction for UAV imagery with geometric priors"
readme = "README.md"
authors = [{ name = "yanxian" }]
requires-python = ">=3.10.0"
dependencies = [
    "huggingface_hub",
    "hydra-core",
    "lpips",
    "natsort",
    "opencv-python-headless==4.10.0.84",
    "OpenEXR",
    "orjson",
    "pillow-heif",
    "plyfile",
    "python-box",
    "requests",
    "rerun-sdk~=0.24.1",
    "safetensors",
    "tensorboard",
    "tqdm",
    "trimesh",
    "uniception==0.1.6",
]

[project.optional-dependencies]
data = ["pandas"]
dev = ["pre-commit", "pytest", "pytest-cov", "ruff"]
all = [
    "geoff3d[data]",
    "geoff3d[dev]",
]

# Setuptools configuration
[tool.setuptools.packages.find]
include = ["geoff3d*"]

[tool.setuptools.package-data]
"geoff3d" = ["**/*"]

[tool.ruff]
lint.extend-select = ["I"]
target-version = "py310"

[tool.ruff.lint.isort]
case-sensitive = false
combine-as-imports = true
detect-same-package = false
order-by-type = false
known-first-party = ["geoff3d", "uniception"]
