slam:
  mode: generic_feedforward_slam

input:
  image_dir: null
  priors: null
  max_frames: null
  stride: 1

frontend:
  chunk_size: 8
  overlap: 1
  min_chunk_size: 2

model:
  name: geoff3d
  auto_load: true
  model_name: geoff3d
  device: cuda
  machine: aws

backend:
  type: no_opt

mapping:
  type: pointcloud
