slam:
  mode: generic_feedforward_slam

input:
  type: image_folder
  image_dir: null
  priors: null
  cams_dir: null
  num_frames: null
  max_frames: null
  stride: 1
  resize: null

frontend:
  chunk_size: 8
  overlap: 1
  min_chunk_size: 2

model:
  name: pi3x
  auto_load: true
  model_name: pi3x
  device: cuda
  machine: aws
  data_norm_type: identity
  hydra_overrides:
    - model/task=mvs

alignment:
  mode: auto
  allow_se3: true
  allow_sim3: true
  allow_sl4: false
  use_overlap_pose: true
  use_world_translation: true

backend:
  type: no_opt

mapping:
  type: pointcloud
