slam:
  mode: generic_feedforward_slam

input:
  type: image_folder
  image_dir: null
  priors: null
  cams_dir: null
  num_frames: null
  max_frames: null
  stride: 1
  resize: null

frontend:
  chunk_size: 16
  overlap: 2
  min_chunk_size: 8

model:
  name: vggt
  auto_load: true
  model_name: vggt
  device: cuda
  machine: aws

alignment:
  mode: auto
  allow_se3: true
  allow_sim3: true
  allow_sl4: false
  use_overlap_pose: true
  use_world_translation: false

backend:
  type: no_opt

mapping:
  type: pointcloud
