# String for model factory (Options: "geoff3d", "pi3x", "vggt")
model_str: ???
# Input image size must be divisible by the model patch size.
patch_size: ???
# Model config
model_config:
  # Path to pretrained model checkpoint
  pretrained_checkpoint_path: null
  # Load specific submodules from the checkpoint
  load_specific_pretrained_submodules: False
  # List of submodules to load from the checkpoint (if load_specific_pretrained_submodules is True)
  specific_pretrained_submodules: []
# Optional starting checkpoint.
pretrained: null
# Image normalization type
data_norm_type: ???
# Torch hub force reload
torch_hub_force_reload: False
