defaults:
  - default
  - task: geoff3d_training

model_str: "geoff3d"
patch_size: 14

model_config:
  name: "geoff3d"
  load_pretrained_weights: true
  geometric_input_config: ${model.task}
  pretrained_model_name_or_path: "checkpoints/pi3x"
  gradient_checkpointing: true

data_norm_type: "identity"
pretrained: null
torch_hub_force_reload: False
