defaults:
  - default

# Number of views parameter for the multi-view datasets
num_views: 2

# Covisibility threshold for the multi-view datasets
covisibility_thres_min: 0.3
covisibility_thres_max: 1.0

# Sampling mode for the A3D dataset
sampling_mode: "random_walk" 

# Test Resolution
resolution_test_a3dreal: ${dataset.resolution_options.518_1_52_ar}
resolution_test_usegeo: ${dataset.resolution_options.518_1_33_ar} 

# Test Set
# usegeo: Sample 20 multi-view sets from each scene, 3 test scenes in total
# a3d-real: Sample 10 multi-view sets from each scene, 27 test scenes in total

test_dataset:
  "+ 60 @ ${dataset.usegeo_wai.test.dataset_str}
  + 270 @ ${dataset.a3dreal_wai.test.dataset_str}"
