Weights:
  model: 'VGGT'
  VGGT: '/opt/data/private/code/map-anything/checkpoints/vggt/model.pt'
  Pi3: './weights/Pi3/model.safetensors'
  Map: './weights/map_anything'
  DBoW: './weights/ORBvoc.txt'
  SALAD: '/opt/data/private/code/map-anything/checkpoints/torch_cache/hub/checkpoints/dino_salad.ckpt'
  DNIO: '/opt/data/private/code/map-anything/checkpoints/torch_cache/hub/checkpoints/dinov2_vitb14_pretrain.pth'

Model:
  chunk_size: 8
  overlap: 4
  loop_chunk_size: 4
  loop_enable: False
  useDBoW: False
  delete_temp_files: True
  align_method: 'numpy'
  using_sim3: True
  reference_frame_mid: False
  calib: False
  h: 376
  w: 1241

  IRLS:
    delta: 0.1
    max_iters: 5
    tol: 1e-9

  Pointcloud_Save:
    sample_ratio: 0.015
    conf_threshold_coef: 0.75
    use_confidence_filtering: true

Loop:
  DBoW:
    thresh: 0.034
    num_repeat: 3
    NMS: 25

  SALAD:
    image_size: [336, 336]
    batch_size: 32
    similarity_threshold: 0.85
    top_k: 5
    use_nms: True
    nms_threshold: 25

  SIM3_Optimizer:
    lang_version: 'python'
    max_iterations: 30
    lambda_init: 1e-6
